### ISSUE TITLE
Add a timer to limit autocompletion calls

### ISSUE THREAD

**Issue by haubourg** [Oslandia/french_locator_filter#1]
To avoid overloading the server providing the location service, it would be nice to add delay to limit the calls. 
200ms could be a nice default value

**Comment by garaud** [comment]
200ms between which action? Just type a letter in the search input form.

Another idea, it's to allow the autocompletion with a minimum number of letter, 3 or 4 for instance.

**Comment by Niarolf** [comment]
A timer between the end of user writing and api request sending in order to avoid send query which will not be use by qgis or the user.

**Comment by haubourg** [comment]
In fact, the Nominatim plugin disallows autocompletion calls, and in this version, the user has to type on the space bar to trigger a search. It is also allowed to search only with string longer than 3 characters. 
This is not especially easy to use. I prefer the idea of triggering a call only when typing is idle for more than 200ms.

**Comment by haubourg** [comment]
> Another idea, it's to allow the autocompletion with a minimum number of letter, 3 or 4 for instance.

we already limit to 2 letters before triggering the search. We can raise to 3 if needed. 
Adding a timer is not so trivial given that this the search are threaded. I didn't find any built-in method at this point in QGIS classes.

**Comment by delhomer** [comment]
The project is being migrated. The discussion can be pursued at https://gitlab.com/Oslandia/qgis/french_locator_filter/-/issues/1
