### ISSUE TITLE
Support more http error codes

### ISSUE THREAD

**Issue by haubourg** [Oslandia/french_locator_filter#2]
It would be nice to support also the following redirection [codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) :

- 301 Moved Permanently
    This and all future requests should be directed to the given URI.[21]

- 302 Found (Previously "Moved temporarily")
    Tells the client to look at (browse to) another URL. 302 has been superseded by 303 and 307. This is an example of industry practice contradicting the standard. The HTTP/1.0 specification (RFC 1945) required the client to perform a temporary redirect (the original describing phrase was "Moved Temporarily"),[22] but popular browsers implemented 302 with the functionality of a 303 See Other. Therefore, HTTP/1.1 added status codes 303 and 307 to distinguish between the two behaviours.[23] However, some Web applications and frameworks use the 302 status code as if it were the 303.[24]

- 303 See Other (since HTTP/1.1)
    The response to the request can be found under another URI using the GET method. When received in response to a POST (or PUT/DELETE), the client should presume that the server has received the data and should issue a new GET request to the given URI.[25]

- 304 Not Modified (RFC 7232)

    Indicates that the resource has not been modified since the version specified by the request headers If-Modified-Since or If-None-Match. In such case, there is no need to retransmit the resource since the client still has a previously-downloaded copy.[26]

- 307 Temporary Redirect (since HTTP/1.1)
    In this case, the request should be repeated with another URI; however, future requests should still use the original URI. In contrast to how 302 was historically implemented, the request method is not allowed to be changed when reissuing the original request. For example, a POST request should be repeated using another POST request.[29]
    In this case, the request should be repeated with another URI; however, future requests should still use the original URI. In contrast to how 302 was historically implemented, the request method is not allowed to be changed when reissuing the original request. For example, a POST request should be repeated using another POST request.[29]

**Comment by delhomer** [comment]
The project is being migrated. The discussion can be pursued at https://gitlab.com/Oslandia/qgis/french_locator_filter/-/issues/2
